name: Update MTA RSS Feed

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: 

# This tells GitHub to use the new engine and silences the deprecation warning
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run MTA Scraper Script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python mta_scraper.py

    - name: Commit and push tracking changes back to GitHub
      run: |
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "actions@github.com"
        git add seen_alerts.txt
        git diff-index --quiet HEAD || git commit -m "Update alert history log"
        git pull --rebase origin main
        git push origin main
